Algoritmo "salario maior ou menor que o minimo"

Var

   nome: caractere;
   salario: real,

Inicio
   escreva("Digite seu  nome")
   leia(nome)
   escreva ("Digite o salário")
   leia(salario)
   se(salario>1200)entao
      escreval(" Seu salário é maior que o salário minimo!!!")
   senao
      se (salario=1200)entao
         escreval("Seu salário é igual ao salário minimo !!!")
      senao
         escreval("Seu salário é menor que o salário minimo !!!")
      fimse
   fimse



Fimalgoritmo